### PR TITLE
Allow project to be a template

### PR DESCRIPTION
**Pull request by rendaz**

### CODE REVIEW

**Comment by jamesward** [comment]
What is the purpose of `tarball/canvas-quickstart-java.tgz` ?

**Comment by rendaz** [comment]
The tgz file is used by heroku to do a quick deploy. I think this file is typically added automatically by heroku if you link the project to a heroku project. 

Here is a link to heroku about this feature: [Heroku Quick Deploy Button](https://devcenter.heroku.com/articles/heroku-button)

**Comment by jamesward** [comment]
@rendaz You definitely shouldn't need to put a tgz in the repo to use Heroku Button.

**Comment by rendaz** [comment]
I did some more research and it appears that github will auto create a tarball located at github.com/username/project/tarball/master. I should be able to use that, so this part of the commit is unnecessary, good catch @jamesward !

**Review by mpsenn — COMMENTED** [review]
Good work!

**Pull request merged**
